version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - mkdir build-output
      - cp -R index.js node_modules/ build-output
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://build-output.zip
      - echo "DONE!!"
artifacts:
  files:
    - build-output/**/*
