version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
  post_build:
    commands:
      - mkdir build-output
      - cp -R index.js node_modules/ build-output
  artifacts:
    files:
      - build-output/**/*